# /Users/tsta0015/Programming/eris/mkdocs.yml
site_name: "eris 🧬🧞‍♀🔮️"
site_url: https://tomdstanton.github.io/eris
repo_url: https://github.com/tomdstanton/eris
site_description: "Uncovering IS-mediated discord in bacterial genomes."
repo_name: "tomdstanton/eris"
watch: [mkdocs.yml, README.md, src]

nav:
  - Home: index.md

theme:
  name: "material"
  icon:
    logo: 'material/dna'
  homepage: https://tomdstanton.github.io/eris
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.follow
    - content.action.edit

markdown_extensions:
  - admonition
#  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: "google"
  - api-autonav:
      modules: ['src/eris']
      nav_section_title: "API Reference"