[project]
authors = [{name = "Tom Stanton", email = "tomdstanton@gmail.com"}]
name = "eris"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = ["pyrodigal>=3.6.3.post1,<4", "pyhmmer>=0.11.1,<0.12", "mappy>=2.30,<3"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["bioconda", "conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
eris = { path = ".", editable = true }

[tool.pixi.tasks]
