# .github/workflows/docs.yml
name: docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # Your pyproject.toml requires >= 3.9. Pinning to a specific version
          # ensures your builds are stable and reproducible.
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          # Create a cache key based on the runner's OS, Python version,
          # and a hash of your pyproject.toml. This is the most reliable way.
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install .[docs]

      - name: Deploy documentation
        run: python -m mkdocs gh-deploy --force